services:
  api:
    build: .
    container_name: car-rental-api
    env_file:
      - .env.docker
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: car-rental-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 5534
      MYSQL_DATABASE: carrental_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p5534 --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: car-rental-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

networks:
  default:
    name: car-rental-net
